experiments:
  - dataset: "cifar10"
    num_rounds: 100
    num_clients: 10
    data_split: "iid"
    participation: 1.0
    max_parallel_executions: 6
    skewness_alpha: 0.1
    seed: 1

  # - dataset: "cifar10"
  #   num_rounds: 100
  #   num_clients: 10
  #   data_split: "iid"
  #   participation: 1.0
  #   max_parallel_executions: 6
  #   skewness_alpha: 0.1
  #   seed: 1

  # - dataset: "cifar10"
  #   num_rounds: 100
  #   num_clients: 10
  #   data_split: "iid"
  #   participation: 1.0
  #   max_parallel_executions: 6
  #   skewness_alpha: 0.1
  #   seed: 1

  # - dataset: "cifar10"
  #   num_rounds: 100
  #   num_clients: 10
  #   data_split: "iid"
  #   participation: 1.0
  #   max_parallel_executions: 6
  #   skewness_alpha: 0.1
  #   seed: 1