experiments:
  - dataset: "cifar10"
    num_rounds: 100
    num_clients: 10
    data_split: "iid"
    participation: 1.0
    max_parallel_executions: 5
    skewness_alpha: 0.1
    seed: 1
    class_aware: True
    uncertainty: "norm"

#  - dataset: "cifar10"
#    num_rounds: 100
#    num_clients: 10
#    data_split: "iid"
#    participation: 1.0
#    max_parallel_executions: 6
#    skewness_alpha: 0.1
#    seed: 1
#    class_aware: True
#    uncertainty: "norm"
#
#  - dataset: "svhn"
#    num_rounds: 100
#    num_clients: 10
#    data_split: "iid"
#    participation: 1.0
#    max_parallel_executions: 6
#    skewness_alpha: 0.1
#    seed: 1
#    class_aware: True
#    uncertainty: "norm"
#
#  - dataset: "svhn"
#    num_rounds: 100
#    num_clients: 10
#    data_split: "dir_balance"
#    participation: 1.0
#    max_parallel_executions: 6
#    skewness_alpha: 0.1
#    seed: 1
#    class_aware: True
#    uncertainty: "norm"
